# -*- coding: utf-8 -*-
"""yolov5_optimize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7vYsDLrHAXR1uGnG-Sm7Uphnpv4bRZr
"""

#!/usr/bin/env python3
# optimize_onnx.py

import argparse
import onnx

# ✅ YOLOv5에서 export한 ONNX도 최적화 가능
from ktc.onnx_optimizer_1_13 import onnx2onnx_flow

def optimize_onnx(input_path: str, output_path: str):
    # 1) ONNX 모델 로드
    model = onnx.load(input_path)

    # 2) 최적화 수행 (YOLOv5 export 기준 구조도 지원됨)
    optimized = onnx2onnx_flow(model, eliminate_tail=True)

    # 3) 최적화 모델 저장
    onnx.save(optimized, output_path)
    print(f"✅ ONNX 최적화 완료: {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="YOLOv5용 ONNX 최적화")
    parser.add_argument("--input",  required=True, help="원본 ONNX 파일 경로 (예: best.onnx)")
    parser.add_argument("--output", required=True, help="최적화된 ONNX 저장 경로 (예: best_opt.onnx)")
    args = parser.parse_args()
    optimize_onnx(args.input, args.output)